apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-resource-quota
  namespace: default
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 3Gi
    pods: "3"
    secrets: "5"
    services: "5"