name: abc
on:
  pull_request:
  push:
    branches: [main]
jobs:
  testenv:
    runs-on: ubuntu-22.04
    steps:
      - name: Print Env
        run: 'echo "Env: ${{ env.ENV }}"'

      - name: Print Secret
        run: 'echo "Secret: ${{ secrets.MY_SECRET }}"'
