# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "azurerm" {
  features {
    resource_group {
      prevent_deletion_if_contains_resources = false
    }
  }
  # default_tags {
  #   tags = {
  #     ApplicationName = "Azure-IaC"
  #     Creator         = "TinNT26"
  #     OwnerService    = "CuongNV61"
  #     ProjectID       = "GHSPOC2019"
  #     CreatedBy      = "Terraform"
  #   }
  # }
}
